### PR TITLE
Update extension setup

### PR DESCRIPTION
**Pull request by adswa**
Work towards fixing #3

### CODE REVIEW

**Comment by adswa** [comment]
Who knows what's needed to satisfy the docbuild?

**Comment by mslw** [comment]
Playing around locally, it seems that it's just about which pieces are commented out in `docs/source/index.rst`. Throwing away some stuff helped. I'll propose changes in a moment, once I figure out the least invasive intervention.

**Comment by adswa** [comment]
merci :)

**Review by mih — APPROVED** [review]
Looks good! Thx!

Merging immediately, as this puts the CI in business again.

**Pull request merged**
