### PR TITLE
DOC: adds datalad-debian logo + variant with names

### LINKED ISSUE #27: Create logo/artwork
I think this project is worthy of its own little extension logo. Maybe we can blend Debian and DataLad. :)

### PR DESCRIPTION
**Pull request by jsheunis**
This PR adds two vector image files:
- one with the proposed datalad-debian logo
- one with the same logo and the names added

The images are located in `docs/source/_static`

Closes #27

### CODE REVIEW

**Comment by mih** [comment]
Looking at the "DataLad" coloring -- it somewhat feels as if the "l" should be yellow. WDYT?

**Comment by jsheunis** [comment]
Agreed! Completely missed it but it makes sense :)

**Review by adswa — APPROVED** [review]
Really cool!

**Review by mih — APPROVED** [review]
Perfect! Thx!

**Pull request merged**
